local plr = game.Players.LocalPlayer

hasFeinted = false
spawn(function()
while wait() do
if hasFeinted == true then
wait()
hasFeinted = false
end
end
end)

while wait() do
pcall(function()
local CharacterFolder =  workspace.Characters:GetChildren()

for i,v in pairs(CharacterFolder) do

if v.StatusFolder:FindFirstChild('Stun') or v.StatusFolder:FindFirstChild('Stun1') then
local pos = v.HumanoidRootPart.Position - plr.Character.HumanoidRootPart.Position
if pos.Magnitude <= 15 and v.Name ~= plr.Name then
	local args = {
		[1] = "M1"
	}
	
	game:GetService("Players").LocalPlayer.Character.Sword.ComboEvent:FireServer(unpack(args))
end
end
if v.StatusFolder:FindFirstChild('FeintCD') then
local pos = v.HumanoidRootPart.Position - plr.Character.HumanoidRootPart.Position
if pos.Magnitude <= 20 and v.Name ~= plr.Name then
if hasFeinted == false then
hasFeinted = true
local args = {
    [1] = "Start"
}

game:GetService("Players").LocalPlayer.Character.Roll.RemoteEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Cancel",
    [2] = {
        ["Instance"] = workspace.Baseplate,
        ["Normal"] = Vector3.new(0, 1, 0),
        ["Position"] =game.Players.LocalPlayer.Character.HumanoidRootPart.Position
    }
}
end
game:GetService("Players").LocalPlayer.Character.Roll.RemoteEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
local args = {
    [1] = "F"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
local args = {
    [1] = "End"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "M1"
}

game:GetService("Players").LocalPlayer.Character.Sword.ComboEvent:FireServer(unpack(args))
local args = {
    [1] = "F"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
local args = {
    [1] = "End"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
end
end
if v.StatusFolder:FindFirstChild('Hitting') then
local pos = v.HumanoidRootPart.Position - plr.Character.HumanoidRootPart.Position
if pos.Magnitude <= 17 and v.Name ~= plr.Name then
feintorparry = math.random(1,2)
if feintorparry == 1 then
-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "F"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
wait()
local args = {
    [1] = "F"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
local args = {
    [1] = "End"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
local args = {
    [1] = "End"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
elseif feintorparry == 2 and hasFeinted == false then
local args = {
    [1] = "Start"
}

game:GetService("Players").LocalPlayer.Character.Roll.RemoteEvent:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Cancel",
    [2] = {
        ["Instance"] = workspace.Baseplate,
        ["Normal"] = Vector3.new(0, 1, 0),
        ["Position"] =game.Players.LocalPlayer.Character.HumanoidRootPart.Position
    }
}

game:GetService("Players").LocalPlayer.Character.Roll.RemoteEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
local args = {
    [1] = "F"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
local args = {
    [1] = "End"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "M1"
}

game:GetService("Players").LocalPlayer.Character.Sword.ComboEvent:FireServer(unpack(args))
local args = {
    [1] = "F"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
local args = {
    [1] = "End"
}

game:GetService("Players").LocalPlayer.Character.Sword.BlockEvent:FireServer(unpack(args))
end
end
end
end
end)
end

